package com.alerts;

import com.cardio_generator.outputs.OutputStrategy;
import java.util.ArrayList;
import java.util.List;

/**
 * The {@code AlertManager} class is responsible for receiving, storing, and dispatching alerts
 * generated by the AlertGenerator. It can be extended to notify medical staff, log alerts,
 * or perform other alert management tasks.
 */
public class AlertManager {
    private List<Alert> activeAlerts = new ArrayList<>();

    /**
     * Receives a new alert and processes it (e.g., stores or dispatches).
     *
     * @param alert the alert to be managed
     */
    public void dispatchAlert(Alert alert) {
        // Store the alert (could be extended to notify staff, etc.)
        activeAlerts.add(alert);
    }

    /**
     * Returns a list of currently active alerts.
     *
     * @return list of active alerts
     */
    public List<Alert> getActiveAlerts() {
        return new ArrayList<>(activeAlerts);
    }
}